{
 "title": "EBIS Observabilidad Local",
 "tags": [
  "ebis",
  "besu",
  "tfm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidad de servicios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} {{node}}{{service}}" }
   ]
  },
  {
   "title": "Altura de bloque por nodo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ethereum_blockchain_height", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Peers Besu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ethereum_peer_count", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Throughput API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[2m])) by (uri, status)",
     "legendFormat": "{{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latencia API promedio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[5m])) / sum(rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Transacciones on-chain acumuladas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "besu_blockchain_chain_head_transaction_count_counter_total{job=\"besu\", node=\"rpcnode\"}",
     "legendFormat": "rpcnode"
    }
   ]
  },
  {
   "title": "Logs relevantes del demo",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{compose_project=\"ebis-nacionalidad-ledger\", compose_service=~\"api|rpcnode|validator1|validator2|validator3|validator4|otel-collector|prometheus|grafana|loki|tempo\"}"
    }
   ]
  }
 ]
}