genesis-file="/config/genesis.json"
data-path="/data"
profile="ENTERPRISE"

p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=true

rpc-http-enabled=false
rpc-ws-enabled=false
graphql-http-enabled=false

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

min-gas-price=0
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/data/permissions_config.toml"

host-allowlist=["*"]
logging="INFO"

