#!/usr/bin/env bash
set -euo pipefail

BESU_VERSION="${BESU_VERSION:-26.6.1}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BESU_DIR="${ROOT_DIR}/blockchain/besu"
GENERATED_DIR="${BESU_DIR}/generated"
NETWORK_FILES_DIR="${GENERATED_DIR}/networkFiles"

# Besu validates bootnode enode URLs as literal IPs (Docker Compose service
# hostnames are not resolved), so nodes get the static IPs pinned in
# infra/compose.yaml's `besu` network (172.24.0.0/24).
RPC_IP="172.24.0.15"
validator_ip() {
  echo "172.24.0.1$1"
}

if [ -f "${GENERATED_DIR}/genesis.json" ]; then
  echo "Genesis already generated in ${GENERATED_DIR}; skipping (use 'make reset-demo' to regenerate)."
  exit 0
fi

mkdir -p "${GENERATED_DIR}"

docker run --rm \
  -u "$(id -u):$(id -g)" \
  -v "${BESU_DIR}:/work" \
  "hyperledger/besu:${BESU_VERSION}" \
  operator generate-blockchain-config \
  --config-file=/work/qbftConfigFile.json \
  --to=/work/generated/networkFiles \
  --private-key-file-name=key

cp "${NETWORK_FILES_DIR}/genesis.json" "${GENERATED_DIR}/genesis.json"

validator_dirs=()
while IFS= read -r dir; do
  validator_dirs+=("${dir}")
done < <(find "${NETWORK_FILES_DIR}/keys" -mindepth 1 -maxdepth 1 -type d | sort)

if [ "${#validator_dirs[@]}" -ne 4 ]; then
  echo "Expected 4 validator key directories, found ${#validator_dirs[@]}" >&2
  exit 1
fi

rm -rf "${GENERATED_DIR}/validator1" "${GENERATED_DIR}/validator2" "${GENERATED_DIR}/validator3" "${GENERATED_DIR}/validator4" "${GENERATED_DIR}/rpcnode"

bootnodes=()

for idx in 1 2 3 4; do
  src="${validator_dirs[$((idx - 1))]}"
  dest="${GENERATED_DIR}/validator${idx}"
  mkdir -p "${dest}/data"
  cp "${src}/key" "${dest}/data/key"
  cp "${src}/key.pub" "${dest}/data/key.pub"
  pubkey="$(tr -d '\n' < "${dest}/data/key.pub")"
  pubkey="${pubkey#0x}"
  enode="enode://${pubkey}@$(validator_ip "${idx}"):30303"
  bootnodes+=("${enode}")
  printf '%s\n' "${enode}" > "${dest}/enode"
done

mkdir -p "${GENERATED_DIR}/rpcnode/data"
openssl rand -hex 32 > "${GENERATED_DIR}/rpcnode/data/key"
docker run --rm \
  -u "$(id -u):$(id -g)" \
  -v "${GENERATED_DIR}/rpcnode/data:/data" \
  "hyperledger/besu:${BESU_VERSION}" \
  public-key export --to=/data/key.pub --node-private-key-file=/data/key
rpc_pubkey="$(tr -d '\n' < "${GENERATED_DIR}/rpcnode/data/key.pub")"
rpc_pubkey="${rpc_pubkey#0x}"
rpc_enode="enode://${rpc_pubkey}@${RPC_IP}:30303"
printf '%s\n' "${rpc_enode}" > "${GENERATED_DIR}/rpcnode/enode"

all_nodes=("${bootnodes[@]}" "${rpc_enode}")
bootnodes_csv="$(IFS=,; echo "${bootnodes[*]}")"
printf '%s\n' "${bootnodes_csv}" > "${GENERATED_DIR}/bootnodes"

permissions_line='nodes-allowlist=['
for i in "${!all_nodes[@]}"; do
  if [ "${i}" -gt 0 ]; then
    permissions_line+=","
  fi
  permissions_line+="\"${all_nodes[$i]}\""
done
permissions_line+=']'

for node in validator1 validator2 validator3 validator4 rpcnode; do
  printf '%s\n' "${permissions_line}" > "${GENERATED_DIR}/${node}/data/permissions_config.toml"
  printf '%s\n' "${bootnodes_csv}" > "${GENERATED_DIR}/${node}/bootnodes"
done

write_bootnodes_toml_array() {
  local output='['
  for i in "${!bootnodes[@]}"; do
    if [ "${i}" -gt 0 ]; then
      output+=","
    fi
    output+="\"${bootnodes[$i]}\""
  done
  output+=']'
  printf '%s' "${output}"
}

bootnodes_toml="$(write_bootnodes_toml_array)"

for node in validator1 validator2 validator3 validator4; do
  cat > "${GENERATED_DIR}/${node}/config.toml" <<EOF
genesis-file="/config/genesis.json"
tx-pool="legacy"
data-path="/data"
profile="ENTERPRISE"

p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=true
bootnodes=${bootnodes_toml}

rpc-http-enabled=false
rpc-ws-enabled=false
graphql-http-enabled=false

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

min-gas-price=0
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/data/permissions_config.toml"

host-allowlist=["*"]
logging="INFO"
EOF
done

cat > "${GENERATED_DIR}/rpcnode/config.toml" <<EOF
genesis-file="/config/genesis.json"
tx-pool="legacy"
data-path="/data"
profile="ENTERPRISE"

p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=true
bootnodes=${bootnodes_toml}

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH","NET","WEB3","QBFT"]
rpc-http-cors-origins=["http://localhost:5173"]
rpc-ws-enabled=false
graphql-http-enabled=false

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

min-gas-price=0
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/data/permissions_config.toml"

host-allowlist=["localhost","127.0.0.1","rpcnode","api"]
logging="INFO"
EOF

cat > "${GENERATED_DIR}/README.generated.md" <<EOF
# Generated Besu network

Generated by \`scripts/besu-generate-network.sh\` using \`hyperledger/besu:${BESU_VERSION}\`.

This directory contains local development keys and must not be committed.

Validators:
$(printf -- '- %s\n' "${bootnodes[@]}")

RPC node:
- ${rpc_enode}
EOF

echo "Generated Besu network files in ${GENERATED_DIR}"
